### ISSUE TITLE
Some apps do not have an AFloat menu

### ISSUE THREAD

**Issue by Jaydar** [jslegendre/AfloatX#10]
Xcode,Simulator .
This feature is especially needed when using Simulator

**Comment by augustosamame** [comment]
+1 the only app I need to pin on top is the simulator :(

**Comment by w0lfschild** [comment]
Try opening the menu multiple times, it does eventually show up for me.

![Screen Shot 2020-04-13 at 11 04 41 AM](https://user-images.githubusercontent.com/1920148/79146083-aa009800-7d76-11ea-84b9-8aab2e4049f8.png)

**Comment by Jaydar** [comment]
> 尝试多次打开菜单，它最终会显示给我。
> 
> ![屏幕截图2020-04-13 at 11 04 41 AM](https://user-images.githubusercontent.com/1920148/79146083-aa009800-7d76-11ea-84b9-8aab2e4049f8.png)

**Comment by Jaydar** [comment]
> Try opening the menu multiple times, it does eventually show up for me.
> 
> ![Screen Shot 2020-04-13 at 11 04 41 AM](https://user-images.githubusercontent.com/1920148/79146083-aa009800-7d76-11ea-84b9-8aab2e4049f8.png)


I also tried many times, and still no success

**Comment by mvaneijgen** [comment]
I also need this only for the Simulator. Did anyone find any solution fro this or an alternative?

**Comment by jslegendre** [comment]
As of MacForge 0.14.2 injection has been reworked and AfloatX now loads into Simulator. Make sure you're on the latest version!
