### ISSUE TITLE
Installing without MacForge...?

### ISSUE THREAD

**Issue by jtn99994** [jslegendre/AfloatX#14]
I started installing MacForge (just to install AfloatX) but I'm not a programmer and when I got to the part where it asks me to disable system integrity protection, I did a 180 and uninstalled MacForge.

Is there any other way to install the AfloatX bundle that doesn't require me to compromise my OS in ways I understand nothing about?

**Comment by jslegendre** [comment]
It is not possible to use AfloatX or any other plugins with SIP enabled.  This is not a limitation of MacForge, it is a limitation of macOS itself. See https://github.com/jslegendre/AfloatX/issues/12
