### ISSUE TITLE
Feature Request: Visor mode

### ISSUE THREAD

**Issue by j0hnm4r5** [jslegendre/AfloatX#15]
Add the ability to pop in (animation optional, I suppose) a window from any one of the screen edges, and have it pop out when focus is lost.

You could bind the windows to hot keys, and have them appear on top of anything, wherever you are. Imagine being able to pull a terminal or a Finder window up with a key press at any time.

iTerm has it built in, and I’ve used TotalFinder for the longest time to add it to Finder, but it would be nice to do it on any window.

**Comment by jslegendre** [comment]
I like this. I'll do some investigating but my gut tells me this might be out of scope for this project. If so, this may become its own project.
