### ISSUE TITLE
Big Sur: AfloatX launch bug causing desktop/dock/menu bar to become unresponsive/greyed out 

### ISSUE THREAD

**Issue by kevinjohncutler** [jslegendre/AfloatX#17]
When I restart my system or just MacForge with AfloatX enabled, the menu bar goes gray and desktop navigation stops working (no dock, gestures to show desktop, etc.). It can be fixed by 'disabling injection' from the macforge menu bar dropdown. Any apps that were open still have the AfloatX context menu too (I only use the inversion, which as I mentioned in another thread now works like a charm). 

As far as I can tell, MacForge is not the issue -  disabling AfloatX and relaunching MacForge does not reproduce this bug.

**Comment by jamespurnama1** [comment]
I think there's a workaround for now:

1. Enable AfloatX in MacForge
2. In the MacForge menubar select 'disable injection'
3. Re-enable the injection from the menubar
4. Profit $$$

However, if you are using other modules that involve the desktop/dock (e.g. space renamer), those modules will not work. So you have to pick either/or.

**Comment by kevinjohncutler** [comment]
Yep, that's what I've been doing. It just so happens that I use this just for MATLAB, which likes to crash when the display sleeps in macOS, so I have to cycle MacForge a lot haha.

**Comment by dbsubasi** [comment]
> When I restart my system or just MacForge with AfloatX enabled, the menu bar goes gray and desktop navigation stops working (no dock, gestures to show desktop, etc.). It can be fixed by 'disabling injection' from the macforge menu bar dropdown. Any apps that were open still have the AfloatX context menu too (I only use the inversion, which as I mentioned in another thread now works like a charm).
> 
> As far as I can tell, MacForge is not the issue - disabling AfloatX and relaunching MacForge does not reproduce this bug.

I have the same issue... No permanent solution yet!

**Comment by jamespurnama1** [comment]
@kevinjohncutler @dbsubasi There is a new version of MacForge 1.1.0. This fixes the issue.

**Comment by kevinjohncutler** [comment]
Hooray!
