### ISSUE TITLE
Transparency UI remains there on Facetime Call

### ISSUE THREAD

**Issue by steliosaa** [jslegendre/AfloatX#19]
Hello, Amazing plug-in. Working as promised.

I am on Big Sur 11.1, MacBook Pro Early 2015.

Only problem I found is that the transparency UI works fine on some apps like Terminal, TextEdit etc.. But when trying to do a Facetime call, I am able to do make it into a Float window, Sticky Window, Click-Through window and Transparent window. Which is exactly what I want in order to keep working while still making the Facetime call.

HOWEVER, the Transparency UI is stuck there on Facetime call after I set the slider and click the tick. I can no longer change the slider, and not click on the tick. Also, I can no longer ask for the transparency setting again on the same window if I want to change the transparency again. Also the UI is not transparent so my work behind this UI cannot be seen. Click-Through is working though so I can click on my work through the UI. 

I am attaching a screenshot. Any chance to fix this so the transparency UI disappears after clicking the tick? Thank you :)

<img width="328" alt="image" src="https://user-images.githubusercontent.com/26743665/102795262-dad8a880-43ac-11eb-98be-565528d8aa7b.png">

**Comment by jslegendre** [comment]
Going to look into this

**Comment by steliosaa** [comment]
I didn't restart the computer after installing the plugin or MacForge. 
I restarted it now and everything works perfectly.
But have a look if you have the time, maybe it recurs.

Thank you again! Just wanted to let you know so you don't waste so much time on this issue!

**Comment by jslegendre** [comment]
Hey thank you for letting me know! I will close the issue once I have a chance to confirm
