### ISSUE TITLE
Any way to add window filters, like CIColorInvert? 

### ISSUE THREAD

**Issue by kevinjohncutler** [jslegendre/AfloatX#2]
I tried to implement it myself, but I'm just not familiar enough with the programming language to know what (probably small) errors I am making.

**Comment by jslegendre** [comment]
Funnily enough, I did implement an 'invert color' option on the bus a few weeks ago but I chose not to push the feature because I feel like filters are not really in the scope of this project. That being said, the code I used was almost entirely lifted from the [GrayFocus](https://github.com/w0lfschild/GrayFocus/blob/master/GrayFocus/GrayFocus.m) project by @w0lfschild.

**Comment by jslegendre** [comment]
So I reopened this because since this issue was opened 2 more people have asked for this so I'll be adding this feature soon.

**Comment by jslegendre** [comment]
Done

**Comment by kevinjohncutler** [comment]
Thanks so much for implementing the color inversion, I really appreciate it. Turns out that the filter does not quite work as expected for certain UI elements - for example, the navigation pane in Finder, or in my main use case, the Live Editor in MATLAB. Below are some screenshots of what I mean. 

I'll find some time to look at the code myself and see if I can edit it to work for these UI elements. Turns out that GrayFocus also does not work in exactly the same way - the MATLAB turns blank anbd the Finder pane is unaffected Let me know if anything immediately comes to mind :)

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/39454982/70267019-6b1c5f00-1752-11ea-8870-32afa5ef274a.png">
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/39454982/70267047-7bccd500-1752-11ea-8282-7bdc756f169d.png">
GrayFocus:
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/39454982/70267582-9489ba80-1753-11ea-90b2-3a6fe6ec3ed3.png">


<img width="2416" alt="image" src="https://user-images.githubusercontent.com/39454982/70266922-40320b00-1752-11ea-916c-4e494fef4ed1.png">
<img width="2416" alt="image" src="https://user-images.githubusercontent.com/39454982/70266882-30b2c200-1752-11ea-8848-ab38523ead39.png">
GrayFocus:
<img width="2372" alt="image" src="https://user-images.githubusercontent.com/39454982/70267508-74f29200-1753-11ea-8ec5-f92442361fa6.png">
