### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by JamieJ1** [jslegendre/AfloatX#20]
I'm non tech. How exactly do i install this .bundle file for AfloatX (looks like a plugin lego cube)? Does it work with BigSur on Mac M1?

**Comment by LwsBtlr** [comment]
It looks like ti requires MacForge which requires disabling SIP which is a non-starter for me. I suspect it can be installed into /Library somewhere, but I don’t see any documentation on where to manually install it.

**Comment by ibehnam** [comment]
I'm ok with disabling SIP, but MacForge is not available for M1, so can't install AfloatX either.

**Comment by fharper** [comment]
I was able to install MacForge, but no plugins can be installed on M1 Pro and/or macOS Ventura 13.2.1.
