### ISSUE TITLE
*system requirements

### ISSUE THREAD

**Issue by tjallemaal** [jslegendre/AfloatX#29]
Hi!
Sorry to bother, what are the system requirements for `afloatx`? 
Currently I have MacOS `Catalina` installed.

I'm just kinda scared it will break my computer  ..

Best,

Halem

**Comment by jslegendre** [comment]
AfloatX works on 10.12 and up. I actually did all of the initial development of AfloatX on 10.15

**Comment by tjallemaal** [comment]
thanks @jslegendre
