### ISSUE TITLE
Color inversion not affecting side panels and some custom UI elements

### ISSUE THREAD

**Issue by jslegendre** [jslegendre/AfloatX#3]
Seems to work normally with global (screen) color inversion but not with CIFilters. Don't really have much time to work on this myself at the moment so any help/insight is appreciated.

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/39454982/70267019-6b1c5f00-1752-11ea-8870-32afa5ef274a.png">
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/39454982/70267047-7bccd500-1752-11ea-8282-7bdc756f169d.png">
GrayFocus:
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/39454982/70267582-9489ba80-1753-11ea-90b2-3a6fe6ec3ed3.png">

<img width="2416" alt="image" src="https://user-images.githubusercontent.com/39454982/70266922-40320b00-1752-11ea-916c-4e494fef4ed1.png">
<img width="2416" alt="image" src="https://user-images.githubusercontent.com/39454982/70266882-30b2c200-1752-11ea-8848-ab38523ead39.png">
GrayFocus:
<img width="2372" alt="image" src="https://user-images.githubusercontent.com/39454982/70267508-74f29200-1753-11ea-8ec5-f92442361fa6.png">

_Originally posted by @kevinjohncutler in https://github.com/jslegendre/AfloatX/issues/2#issuecomment-562283050_

**Comment by kevinjohncutler** [comment]
It now works properly in Big Sur! No idea why, but I've been loving it. Thanks again so much for implementing it.

**Comment by jslegendre** [comment]
That's awesome! Closing issue
