### ISSUE TITLE
AfloatX doesn't work on Big Sur M1

### ISSUE THREAD

**Issue by DUOLabs333** [jslegendre/AfloatX#33]
I downloaded through Macforge, but when I installed it, nothing happens -- no new option comes up.

**Comment by searleser97** [comment]
same problem here with M1 in Monterrey

**Comment by jslegendre** [comment]
Can either of you confirm if any other plugins are working for you?

**Comment by DUOLabs333** [comment]
Nothing else works for me.

**Comment by jslegendre** [comment]
So this isn't a problem with AfloatX.  Make sure you have the latest beta of MacForge and have set the `-arm64e_preview_abi` boot-arg. 

See: https://www.macenhance.com/docs/general/sip-abi.html

**Comment by searleser97** [comment]
do you know how to install the Beta version? from the official site I can just download the latest stable

**Comment by jslegendre** [comment]
It is available on the Discord server

https://github.com/MacEnhance/appcast/raw/master/Beta/MacForge/MacForge.1.2.0B1.zip

**Comment by searleser97** [comment]
it now crashes when clicking on any menu option :(
