### ISSUE TITLE
Is there a way to install AfloatX without disabling System Integrity Protection?

### ISSUE THREAD

**Issue by Drugoy** [jslegendre/AfloatX#37]
The description provides 2 ways to download AfloatX (directly from GitHub or via MacForge) but only 1 way to install it (via MacForge) which requires disabling System Integrity Protection, which I'd like NOT to do.
Is there a way to install AfloatX without disabling System Integrity Protection?

**Comment by purekimwater** [comment]
I'd actually like to know if there is a way to install AfloatX without Macforge, too.
Not because of disabling System Integrity Protection,
but because 1. Macforge hasn't been updated for years, 2. It's the only plugin I use from Macforge.

**Comment by purekimwater** [comment]
Just wondering about this too,
but unfortunately, after some searching, jslegendre said it's not possible.
see issues [#12 ](https://github.com/jslegendre/AfloatX/issues/12) and [#14](https://github.com/jslegendre/AfloatX/issues/14).

I would like to install it without Macforge tho.
Macforge hasn't been updated for years, and AfloatX is the only plugin I use...

**Comment by Drugoy** [comment]
Well, that's sad to hear, but thanks for finding the answer.

I think it's worth adding to project's description to make things absolutely clear.
