### ISSUE TITLE
Click through transparency

### ISSUE THREAD

**Issue by briandbezerra** [jslegendre/AfloatX#4]
I like to have some windows set to a low transparency percentage in the corner of the screen, but I would like to be able to click through to UI elements of the current screen BEHIND the floating window (for example a tool bar button or a scrolling arrow).

In other words, it would be great to have a way to ignore the floating window when convenient. Maybe a modifier key? 

In any case, thank you for the application. It's a life saver.

**Comment by jslegendre** [comment]
This is entirely possible to do. It would have to be another option in the Dock menu because there would be no other way to toggle it off otherwise. Not sure how well a modifier key would work because (afaik) AfloatX would have to inject a listener into each separate view within the window

**Comment by jslegendre** [comment]
Done!
