### ISSUE TITLE
Afloatx causes applications to crash when you close all of the application's windows and right click the application's dock icon

### ISSUE THREAD

**Issue by dbonner** [jslegendre/AfloatX#6]
Hi,
I am using a MacBook Pro 16 inch with macOS 10.15.3 beta 3.  I am using AfloatX 1.3.0 with the latest MacForge.  This problem occurs every time I take the following steps and can occur for any specific application.
Steps:
1. Close all of the application's windows with the top left window's red x circle
2. The application remains open (black dot beneath it) in the dock. 
3. Right click the dock icon.
4. Then you get a crash.
The example crash report in the screenshot is produced when using the application TextEdit.
I have also copied the entire output of "Problem Details and System Configuration" to the attached text file.
![Screen Shot 2020-01-27 at 7 01 51 pm](https://user-images.githubusercontent.com/241474/73158766-f275c580-4138-11ea-8568-f9e08b3abe33.png)
[Problem Details and System Configuration.txt](https://github.com/jslegendre/AfloatX/files/4116061/Problem.Details.and.System.Configuration.txt)

**Comment by dbonner** [comment]
My MacForge System Information:
![Screenshot 2020-01-27 19 25 43](https://user-images.githubusercontent.com/241474/73159744-5c8f6a00-413b-11ea-8f78-19ec1e301b7b.png)

**Comment by jslegendre** [comment]
Wow, thank you so much for the details. This is happening because AfloatX tries to gather some information about the top-most window before displaying the dock menu and if there is no window... well this happens. Should be a simple fix. Will get on this ASAP. Thanks again!

**Comment by jslegendre** [comment]
Fixed in version 1.3.1. Thanks again!
