### ISSUE TITLE
Feature Request - macports addition

### ISSUE THREAD

**Issue by mdeguzis** [jslegendre/AfloatX#7]
Why use MacForge? Brew has it's issues, and macports is proven and has a very strong support system and library of software. I don't want to have to install yet another OS X software manager.

Functionality notes from MacForge

>    Loading plugins into system applications requires that System Integrity Protection is disabled
>    Loading plugins into some applications may require Apple Mobile File Integrity to be disabled
>    Loading plugins into some applications may require the plugin must be signed and in the /Library directory
>    Applications installed by MacForge may not require SIP to be disabled to function

**Comment by jslegendre** [comment]
MacForge is an injection platform that also has a package manager for user convenience.  You are free to download AfloatX from the releases tab and use it with mySIMBL but I don't recommend it as it will not be receiving any updates in the future.  It's not possible to use AfloatX or any other plugin without a way to inject it into other apps.
