### ISSUE TITLE
AfloatX menu not appearing in apps initially

### ISSUE THREAD

**Issue by NewsGuyTor** [jslegendre/AfloatX#8]
MacForge 0.14.1 is installed with AfloatX 1.3.5 on macOS 10.15.3, both AMFI and SIP is disabled (and reporting so in MacForge.

The menu didn't appear for most apps that launched at boot, but appeared in others after quitting the applications and starting them again. For other apps it didn't appear at all, until it suddenly did after a number of application restarts. Now I've got my apps to have the menu.

I wonder if there's some kind of cache that should be cleared automatically by AfloatX.

**Comment by jslegendre** [comment]
This sounds like more of an issue with MacForge than AX to be honest. MacForge doesn't starts after login so it's quite normal for nothing to be injected until later. It should retroactively inject open apps but it's not perfect.  Were there any particular apps that you had problems getting AX to work with?
